name: MXBukkitLib
anthor: Karlatemp
version: 1.0.0
main: cn.mcres.gyhhy.MXLib.bukkit.Plugin
load: STARTUP
website: https://www.mcres.cn/resources/73/
description: Bukkit Lib
permissions:
    mxlib.update:
        default: true